# -*- coding: utf-8 -*-
"""
Created on Fri Apr 29 23:07:28 2022

@author: cesar
"""


import pyautogui as pa
import random
import time
import pyttsx3
engine=pyttsx3.init()
engine.setProperty("rate", 150)
carta="Hola,Esto es por dejar mucha tarea, pd fue de rapido esto je"
engine.say(carta)
pa.hotkey("win","r")  
time.sleep(.5)
pa.typewrite("cmd")
time.sleep(.5)
pa.hotkey("enter")
time.sleep(.5)
pa.typewrite("start chrome ]]")
time.sleep(.5)
pa.hotkey("enter")
time.sleep(.5)
pa.typewrite("https://www.youtube.com/watch?v=qyYmS_iBcy4")    
time.sleep(1)
pa.hotkey("enter")
pa.hotkey("win","r")  
time.sleep(.5)
pa.typewrite("cmd")
time.sleep(.5)
pa.hotkey("enter")
time.sleep(.5)
pa.typewrite("start chrome ]]")
time.sleep(.5)
pa.hotkey("enter")
time.sleep(.5)
pa.typewrite("https://www.youtube.com/watch?v=DMawWBwHnBU")    
time.sleep(1)
pa.hotkey("enter")
time.sleep(5)
pa.hotkey("win","r")  
time.sleep(.5)
pa.typewrite("cmd")
time.sleep(.5)
pa.hotkey("enter")
time.sleep(.5)
pa.typewrite("start chrome ]]")
time.sleep(.5)
pa.hotkey("enter")
time.sleep(.5)
pa.typewrite("https://www.youtube.com/watch?v=lIyONMmoepU&t=260s")    
time.sleep(1)
pa.hotkey("enter")
pa.hotkey("win", "right")
pa.hotkey("win", "left")
time.sleep(7)

pa.alert("ESTAS SIENDO  HACKEADO")
time.sleep(.5)
pa.alert("NECESITA PONERME 10 EN EL SAES PARA SALVAR SU COMPUTADOR")
time.sleep(.5)
pa.hotkey("win","r")  
time.sleep(.5)
pa.typewrite("cmd")
time.sleep(.5)
pa.hotkey("enter")
time.sleep(.5)
pa.typewrite("shutdown -s -t 40 ")
time.sleep(.5)
pa.typewrite("shutdown -s -t 40 ")
pa.hotkey("enter")
pa.hotkey("enter")
pa.alert("ESTAS SIENDO  HACKEADO")
pa.hotkey("win", "d")
pa.moveTo(x=1300,y=879)
pa.doubleClick(button="right")
for i in range(1, 11):
    pa.hotkey("down")
    time.sleep(.1)
    
pa.hotkey("enter")
for i in range(1, 9):
    pa.hotkey("tab")
    time.sleep(.1)
    
pa.hotkey("enter")
for i in range(1, 4):
    pa.hotkey("down")
    time.sleep(.1)
pa.hotkey("enter")
for i in range(300): 
    pa.moveTo(x=random.randint(10, 1900), y=random.randint(10, 1000))
    print(pa.position())
    pa.hotkey("win", "left")
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "left")
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "d")
    pa.hotkey("win", "prtscr")
    time.sleep(.5)
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "up")
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "up")
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "d")
    pa.hotkey("win", "prtscr")
    time.sleep(.5)
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "down")
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "down")
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "d")
    pa.hotkey("win", "prtscr")
    time.sleep(.5)
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "right")
    pa.hotkey("win", "right")
    pa.hotkey("win", "d")
    time.sleep(.5)
    pa.hotkey("win", "prtscr")
    pa.hotkey("win", "3")
    pa.hotkey("win", "1")
    pa.hotkey("win", "2")
    pa.hotkey("win", "4")
    pa.hotkey("win", "5")
    pa.hotkey("win", "6")

gracias="Gracias, espero mi nueve cinco por que me falto un programa,triste"
engine.say(gracias)